---

# deploy quarkus app backend native image
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-native-backend
spec:
  inputs:
    params:
      - name: postgresql-image
        type: string
        description: The postgresql image to deploy
        default: registry.redhat.io/rhel8/postgresql-10
      - name: postgesql-user
        type: string
        description: login for postgresql database
        default: keycloak
      - name: postgresql-password
        type: string
        description: password for postgresql database
        default: keycloak
      - name: postresql-database
        type: string
        default: root
        description: default database
      - name: database-service-name
        type: string
        default: sso-test-postgresql
      - name: keycloak_url
        type: string
        default: sso-test:8080


  steps:
    - name: deploy-app
      image: quay.io/openshift/origin-cli:latest
      script: |
          #!/usr/bin/env bash

          echo "clean up previous deployments"
          oc delete all --selector app=expenses-backend-quarkus --ignore-not-found

          export KEYCLOAK_URL="$(inputs.params.keycloak_url)/auth/realms/basic"

          oc new-app expenses-backend-quarkus -e POSTGRESQL_USER=$(inputs.params.postgesql-user)  \
                                               -e POSTGRESQL_DATABASE=$(inputs.params.postresql-database) \
                                               -e POSTGRESQL_PASSWORD=$(inputs.params.postgresql-password) \
                                               -e POSTGRESQL_SERVICE_NAME=$(inputs.params.database-service-name) \
                                               -e KEYCLOAK_URL=$KEYCLOAK_URL\
                                               -e KEYCLOAK_INTROSPECT_URL="$KEYCLOAK_URL/protocol/openid-connect/token/introspect" \
                                               -e KEYCLOAK_CLIENT_ID="backend" \
                                               -e KEYCLOAK_SECRET="16c3384b-725d-410d-8107-df3319165f70"
          echo "expose service"
          echo
          oc expose svc/expenses-backend-quarkus
